### ISSUE TITLE
Keystore password?

### ISSUE THREAD

**Issue by Chiliad-Spring** [YeeZTech/YeeZ-Privacy-Computing#2]
步骤11中，keystore的password是什么啊？

**Comment by xchmwang** [comment]
> password

The underlying blockchain in YPC is Ethereum, so we use Ethereum account model, which includes a keystore file and a password, to send related transactions. 

To have a more infomation about Ethereum account model, please follow https://geth.ethereum.org/docs/interface/managing-your-accounts

**Comment by Chiliad-Spring** [comment]
OK！Thanks for help

**Comment by Chiliad-Spring** [comment]
Sorry ，but I created the Ethereum account through metamask (not geth), so where can I get the keystore password?

**Comment by xchmwang** [comment]
Well, if you create your account in metamask, you can first export the private key of your account, and generate a keystore file and a password from private key. 

Please follow https://web3py.readthedocs.io/en/stable/web3.eth.account.html , to generate your keystore file and set a password.

**Comment by Chiliad-Spring** [comment]
Great，thanks！

**Comment by Chiliad-Spring** [comment]
I almost succeeded, but in step 21, when I called request_data function, the monitoring process successfully downloads the analyzer, but at this times ，an error occur:
“
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error code is 0x200e. Please refer to the "Intel SGX SDK Developer Reference" for more details.
”
I searched in SGX Developer Reference and it shows Error 0x200e means 
“The target enclave (32/64 bit or HS/Sim) mode is incompatible with the uRTS mode.”
I'm very confused，SGX is ok on my computer.

**Comment by xchmwang** [comment]
> I almost succeeded, but in step 21, when I called request_data function, the monitoring process successfully downloads the analyzer, but at this times ，an error occur:
> “
> terminate called after throwing an instance of 'std::runtime_error'
> what(): Error code is 0x200e. Please refer to the "Intel SGX SDK Developer Reference" for more details.
> ”
> I searched in SGX Developer Reference and it shows Error 0x200e means
> “The target enclave (32/64 bit or HS/Sim) mode is incompatible with the uRTS mode.”
> I'm very confused，SGX is ok on my computer.

Please try `cmake -DSGX_MODE=Release -DSGX_HW=ON .. && make -j8` when you build the project from source code.

**Comment by Chiliad-Spring** [comment]
Thanks！
