### ISSUE TITLE
Ropsten 

### ISSUE THREAD

**Issue by Chiliad-Spring** [YeeZTech/YeeZ-Privacy-Computing#3]
Ropsten is a little difficult to use (for speed and eth)
How can I change the blockchain from ropsten to YeeZchain or other chain?

**Comment by simple4016** [comment]
Good  question!
The privacy computing layer and the blockchain layer are completely decoupled. we r planning to support YeeZChain or other chain recently.

anyway, we r highly support if anyone in communty can do this.

**Comment by Chiliad-Spring** [comment]
OK，3ks
